import { MigrationInterface, QueryRunner } from "typeorm";
export class Baseline1790121600000 implements MigrationInterface {
 async up(q: QueryRunner): Promise<void> {
  await q.query("CREATE TABLE IF NOT EXISTS \"reglages\" (\"id\" integer PRIMARY KEY AUTOINCREMENT NOT NULL, \"utilisateurId\" integer NOT NULL, \"frequenceSnapshot\" varchar NOT NULL DEFAULT ('fin_de_mois'), \"notifPushWeb\" boolean NOT NULL DEFAULT (1), \"notifEmail\" boolean NOT NULL DEFAULT (1), CONSTRAINT \"UQ_c73b9eee1dcdedde6c1a4b0f860\" UNIQUE (\"utilisateurId\"))");
  await q.query("CREATE TABLE IF NOT EXISTS \"workspace_records\" (\"id\" varchar PRIMARY KEY NOT NULL, \"kind\" varchar NOT NULL, \"data\" text NOT NULL, \"updatedAt\" datetime NOT NULL DEFAULT (datetime('now')))");
  await q.query("CREATE TABLE IF NOT EXISTS \"factures\" (\"id\" integer PRIMARY KEY AUTOINCREMENT NOT NULL, \"or\" varchar, \"factNum\" varchar, \"designation\" varchar, \"mHt\" float, \"tva\" float, \"mTtc\" float, \"iff\" varchar, \"libFrss\" varchar, \"iceFrs\" varchar, \"taux\" float, \"idPaie\" integer, \"datePaie\" varchar, \"dateFac\" varchar, \"sousType\" varchar NOT NULL, \"statut\" varchar NOT NULL DEFAULT ('validee'), \"champsManquants\" text, \"vigilanceRenforcee\" boolean NOT NULL DEFAULT (0), \"utilisateurId\" integer, \"saisiPar\" varchar, \"lotId\" varchar, \"notifiable\" boolean NOT NULL DEFAULT (0), \"documentId\" varchar, \"revueHumaine\" boolean NOT NULL DEFAULT (0), \"demonstration\" boolean NOT NULL DEFAULT (0), \"archivee\" boolean NOT NULL DEFAULT (0), \"doublonDe\" integer, \"rapprocheeA\" integer, \"creeLe\" datetime NOT NULL DEFAULT (datetime('now')), \"modifieLe\" datetime NOT NULL DEFAULT (datetime('now')))");
  await q.query("CREATE TABLE IF NOT EXISTS \"utilisateurs\" (\"id\" integer PRIMARY KEY AUTOINCREMENT NOT NULL, \"nom\" varchar NOT NULL, \"email\" varchar NOT NULL, \"motDePasseHache\" varchar NOT NULL, \"role\" varchar NOT NULL DEFAULT ('comptable'), \"sessionVersion\" integer NOT NULL DEFAULT (0), \"creeLe\" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT \"UQ_6b14325a486fe68d16aa889e4dc\" UNIQUE (\"email\"))");
  await q.query("CREATE TABLE IF NOT EXISTS \"designations\" (\"id\" integer PRIMARY KEY AUTOINCREMENT NOT NULL, \"libelle\" varchar NOT NULL, \"enAttenteConfirmation\" boolean NOT NULL DEFAULT (0), \"creeLe\" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT \"UQ_e6387af74f5e97348f619f55d63\" UNIQUE (\"libelle\"))");
  await q.query("CREATE TABLE IF NOT EXISTS \"journal\" (\"id\" integer PRIMARY KEY AUTOINCREMENT NOT NULL, \"action\" varchar NOT NULL, \"factureId\" integer, \"designationId\" integer, \"utilisateurId\" integer, \"saisiPar\" varchar, \"lotId\" varchar, \"details\" text, \"notifiable\" boolean NOT NULL DEFAULT (0), \"horodatage\" varchar NOT NULL)");
  await q.query("CREATE TABLE IF NOT EXISTS \"notification_etat\" (\"id\" integer PRIMARY KEY AUTOINCREMENT NOT NULL, \"journalId\" integer NOT NULL, \"utilisateurId\" integer NOT NULL, \"lue\" boolean NOT NULL DEFAULT (0), \"traitee\" boolean NOT NULL DEFAULT (0), \"lueLe\" varchar, \"traiteeLe\" varchar)");
  await q.query("CREATE UNIQUE INDEX IF NOT EXISTS \"IDX_22d285bbac4283d2c11d93ff8d\" ON \"notification_etat\" (\"journalId\", \"utilisateurId\") ");
 }
 async down(): Promise<void> { throw new Error("Restaurez la sauvegarde complète dans un dossier distinct."); }
}
